### PR TITLE
small fixes to operators documentation: prop, tag

### PR DESCRIPTION
**Pull request by vendethiel**
## Description

Changes spaces to a tab in the first `prop` since otherwise it wasn't coherent and broke the case.

Inverted "local" and "global" for `tag`.

## Types of changes

* [x] Bug fix \(non-breaking change which fixes an issue\)
* [ ] New feature \(non-breaking change which adds functionality\)
* [ ] Breaking change \(fix or feature that would cause existing functionality to not work as expected\)
* [ ] This change requires a documentation update

## Checklist:

* [x] I have read the **CONTRIBUTING** document.
* [ ] I have updated/added documentation affected by my changes.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by vendethiel** [comment]
Really? I switched it since the docs earlier mention that things starting with an uppercase letter are global, I can undo that part if necessary.

**Comment by familyfriendlymikey** [comment]
Yeah, is this the part of the docs in question?

image

Seems like it might be outdated, I'll confirm with the team and get back to you.

**Comment by familyfriendlymikey** [comment]
> things starting with an uppercase letter are global

This should clarify: https://imba.io/docs/basic-syntax/variables#implicit-self

And with tags it should work as stated in the docs.

**Comment by vendethiel** [comment]
Fixed

**Pull request merged**
