### PR TITLE
Fix 7guis circle-drawer example

### PR DESCRIPTION
**Pull request by codeluggage**
## Description

The 7guis example for `circle-drawer` was broken, this fixes some of it. 

### Open questions

1. The right clicking is wonky. The first few clicks pass through, and then it correctly selects the circles after that. I tried to narrow the allowed selection to only circles, but I can't seem to get the hierarchy of clickable targets right. It seems to work better on Firefox than Chrome. What is the idiomatic Imba way to narrow `@contextmenu` to only `circle` elements, and prevent the right click menu for anything else?
1. Chrome renders the line of the input slider, Firefox does not. Could it have to do with the use of `bxs:md transform: translate(-50%,-50%)`?

## How Has This Been Tested?

Lots and lots of reloading on my local! :)

As a side note, I can't find any tests in this repo so the questions about testing in the PR template may not make sense. 

## Types of changes

* [x] Bug fix \(non-breaking change which fixes an issue\)
* [ ] New feature \(non-breaking change which adds functionality\)
* [ ] Breaking change \(fix or feature that would cause existing functionality to not work as expected\)
* [ ] This change requires a documentation update

## Checklist:

* [x] I have read the **CONTRIBUTING** document.
* [ ] I have updated/added documentation affected by my changes.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Bohooslav** [comment]
To prevent right click, I would better do `return if e.events[-1].buttons !== 1 # Prevent right click`. Works for me in FF and chrome
Also, why do you draw it only on mouse up? I would love to paint circles with slide to make things like these:

image

**Comment by codeluggage** [comment]
> To prevent right click, I would better do `return if e.events[-1].buttons !== 1 # Prevent right click`. Works for me in FF and chrome

This was the first way I did it, actually! Then I noticed `phase` and it somehow seemed easier to read for someone looking through the example. Are there any tradeoffs between those two ways, that you know of? 

> Also, why do you draw it only on mouse up? I would love to paint circles with slide to make things like these:

As each circle is meant to be clickable and resizable with a pop-over modal, it seems to be more of a "click to make circles" example and less of a "draw using circles" example. Perhaps we could have another regular example that lets you set the radius before drawing, so it's more like a "brush size" feeling?

**Comment by Bohooslav** [comment]
I think we should ask @somebee what did he mean creating this example? Should it be a "click to make circles" example or a "draw using circles" example. Should we add a feature like brush size and some other features?

**Comment by codeluggage** [comment]
> I think we should ask @somebee what did he mean creating this example? Should it be a "click to make circles" example or a "draw using circles" example. Should we add a feature like brush size and some other features?

This is my first time doing anything related to the `7guis` concept (https://eugenkiss.github.io/7guis/). You bring up a good question - according to the "spec" it is about clicking and not dragging/drawing. It is not explicitly mentioned, but the screenshot gives a strong indication. 

I'll add the remaining missing requirements as comments so we see what's left to do, too.

**Comment by Bohooslav** [comment]
I made a few fixes of original code written by Sindre and got it working.

image

**Comment by Bohooslav** [comment]
My `fixed` version with undo/redo features. 
https://scrimba.com/scrim/czpwrvCe

**Comment by andregoldstein** [comment]
Nice work @Bohooslav!

Couple of suggestions:

Line `38` change `< 0` to `<= 0` as the undo can throw an error if there are no circles.

`return if !history.length or history_position <= 0`

Spelling of `boundung` to `bounding`

**Comment by codeluggage** [comment]
> My `fixed` version with undo/redo features.
> https://scrimba.com/scrim/czpwrvCe

Nice! 

The circle that has its size changed "pops out" of the undo/redo history for me, and becomes the second to last change to undo 🤔 

As an aside, the addition of undo/redo means that the code is quite a bit longer than what typically fits in the example. Would it make sense to move the management (and also maybe the concept of what an action is - creation or resizing) into its own file? 

Afterwards, would you mind if I added your code into this PR, @Bohooslav?

**Comment by somebee** [comment]
Hey folks. Just as a fun exercise I did a simple code review of the example in a scrim - cleaning up a few things :) https://scrimba.com/scrim/cWbqn4Ta

**Comment by somebee** [comment]
Cool, I now see that @Bohooslav has an example with undo/redo as well. Will take a look at it :)

**Comment by somebee** [comment]
@codeluggage I agree - it makes sense to move the state and history handling into a separate file

**Comment by Bohooslav** [comment]
> Afterwards, would you mind if I added your code into this PR, @Bohooslav?

Wait I will improve it and then you might use it.

**Comment by Bohooslav** [comment]
I reviewed my version of circle drawer, fixed bugs and separated state. https://scrimba.com/scrim/czpwrvCe

**Comment by trafnar** [comment]
Here's my version, which handles all kinds of tricky cases such as undoing, then resizing, then undoing more, or undoing, then resizing then re-doing (this is not allowed in mine as resizing instantly creates a new undo state) etc.

https://scrimba.com/scrim/cW6JMbS6

**Review by familyfriendlymikey — APPROVED** [review]
Checked it out and it works fine for me. Looks good too!

**Pull request merged**
