### PR TITLE
Clean up readme and basic syntax

### PR DESCRIPTION
**Pull request by trafnar**
This is work I did a while back, before @familyfriendlymikey started, so I should get this in here before its too out of date.

The 'basic syntax' is pretty much all covered by https://github.com/imba/imba.io/pull/254, but the same changes exist here, so we should prefer that branch's code for that file (basic-syntax.md).

This PR removes some redundant pages, and simplifies the main nav quite a bit. It also introduces little arrows to indicate which nav sections are toggle-able.

I'm not super tied to any of this so let me know if you think we need to change/ignore any of it.

### CODE REVIEW

**Comment by trafnar** [comment]
Just made some more updates:
- added playground link to the quickstart page
- moved playground link in the nav to the very bottom
- make playground link go to the first example, instead of a blank page

**Comment by trafnar** [comment]
This branch now includes all the work from https://github.com/imba/imba.io/pull/254

So, assuming I didn't lose work or mess anything up from that PR, this one can be used instead and is ready to merge.

**Comment by familyfriendlymikey** [comment]
I rebased onto master for you and fixed the merge conflicts with #254 preferring the changes from this branch. Would be good to make sure the changes look okay to you.

The changes themselves look fine to me! My only review is that I think that the cli, playground, and changelog should stay on the navbar. CLI feels misplaced under `guides`, the playground is what got me into Imba in the first place, and the changelog shows that Imba development is active and is useful to have on the website for power users.

I have some ideas for the navbar as well but maybe we can collab on that later, this is definitely cleaner than before.

**Comment by trafnar** [comment]
I think changelog / playground got removed by mistake. I brought those back inside a section called "Misc" at the bottom. (I don't love that name)

**Comment by trafnar** [comment]
I thought my branch was already merged with #254, I think your rebase removed some of my work (no problem if so, I have it locally)

**Comment by trafnar** [comment]
Ok, I fixed whatever issues I saw from after the rebase, and I reverted most of the changes to the main nav. This is ready for review

**Pull request merged**
