### PR TITLE
clone url fixed

### PR DESCRIPTION
**Pull request by globefire**
Changed `somebee/imba.io.git` to `imba/imba.io`

### CODE REVIEW

**Comment by scanf** [comment]
This has been resolved in https://github.com/imba/imba.io/pull/61

If you are looking for more issues to work on checkout these links
https://github.com/imba/imba/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest
https://github.com/imba/imba.io/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

Thanks.

**Comment by globefire** [comment]
Hey @scanf can you please delete this request as I am making prs for hacktoberfst, this is getting counted in it.

**Comment by scanf** [comment]
I have added a Hacktoberfest label to your merged pull request. 
I think that should be enough to see https://github.com/imba/imba.io/pull/61

The comment is fine as is so don’t see any need to delete it. If I misunderstood you feel free to link me to some official page that explains this.

Thanks.

**Comment by globefire** [comment]
hey @scanf what I am saying is, this closed pr is also counting in my hacktoberfest account, so how do I remove it? Since I accidentally requested twice for the same issue.

hacktober

**Comment by scanf** [comment]
Ah, I see. Unfortunately I don’t have anyway to delete it. The normal workflow is to close the pull request and as far as I can see deleting a pull request is not supported.

You can ask GitHub Support(support@github.com) if it’s important to you.

**Pull request closed without merging**
