### PR TITLE
Applied requested changes to all clocks

### PR DESCRIPTION
**Pull request by Bohooslav**

### CODE REVIEW

**Comment by somebee** [comment]
Thanks for the PR :) It is definitely a point to keep the examples on the frontpage short - so I'd rather try to dig into the FF issues a little before merging, in case it's possible to fix w/o moving all styles out of styles.imba etc :)

**Comment by somebee** [comment]
From what I can see, the only real problem with the clocks in firefox is that it incorrectly renders very large `transform: rotate(1234512342.5turn)` values.

**Comment by somebee** [comment]
https://github.com/imba/imba/commit/dea0196925c578b881b591fb1e9ada66e649c365 Should make the examples work fine in firefox without any changes.

**Comment by codeluggage** [comment]
Working well for me on Firefox `100.0.2` 👍

**Pull request closed without merging**
